
source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
use_frameworks!

target 'CapitalOne Onboarding' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
   pod 'AWSAutoScaling'
    pod 'AWSCloudWatch'
    pod 'AWSCognito'
    pod 'AWSCognitoIdentityProvider'
    pod 'AWSDynamoDB'
    pod 'AWSEC2'
    pod 'AWSElasticLoadBalancing'
    pod 'AWSIoT'
    pod 'AWSKinesis'
    pod 'AWSLambda'
    pod 'AWSLex'
    pod 'AWSMachineLearning'
    pod 'AWSMobileAnalytics'
    pod 'AWSPinpoint'
    pod 'AWSPolly'
    pod 'AWSRekognition'
    pod 'AWSS3'
    pod 'AWSSES'
    pod 'AWSSimpleDB'
    pod 'AWSSNS'
    pod 'AWSSQS'
    pod 'Firebase/Core'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'

  # Pods for CapitalOne Onboarding

  target 'CapitalOne OnboardingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CapitalOne OnboardingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
