# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CapitalOne Onboarding' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CapitalOne Onboarding
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'CapitalOne OnboardingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CapitalOne OnboardingUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
